name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: false
        type: boolean
        default: false

jobs:
  release:
    uses: builtnorth/.github/.github/workflows/composer-package-release.yml@main
    with:
      package-name: 'wp-schema'
      package-display-name: 'WP Schema'
      composer-namespace: 'builtnorth/wp-schema'
      version: ${{ inputs.version }}
      prerelease: ${{ inputs.prerelease }}
    permissions:
      contents: write
